Name: Ranjeet
role: azure consultant
experince: 15

tools:
 - docker
 - kubernetes
 - jenkins
 - monitoring and observing

---
# two ways to write lists in yml
## block Sytle

tools: 
 - docker
 - kuberneties

---
## Block Style
tools: [dockers, kubernities]
